/**
 * app.js - Main Application Orchestrator for Anywhere Offline Music Player PWA
 * 1:1 Pixel-Perfect Alignment to Dribbble & Apple Music iOS Concept References
 */

import { musicStorage } from './storage.js';
import { extractMetadata } from './metadata.js';
import { playerEngine } from './player.js';
import { peerTransfer } from './transfer.js';
import { generateDemoTracks } from './demoTracks.js';

let allSongs = [];
let allPlaylists = [];
let filteredSongs = [];
let currentFilter = 'all';
let searchQuery = '';

let hasUserPlayedAudio = false; // Ensures mini player remains hidden until user interacts

let isMultiSelectMode = false;
let selectedMultiSongIds = new Set();
let longPressTimer = null;

let selectedSongIdsForPlaylist = new Set();
let selectedCoverBlobForPlaylist = null;

let currentActivePlaylistDetail = null;
let currentSourcePlaylistName = null;
let isDraggingSeekbar = false;
let sheetViewMode = 'carousel';

document.addEventListener('DOMContentLoaded', async () => {
  initTabNavigation();
  initPlayerEvents();
  initLibraryEvents();
  initPlaylistModalEvents();
  initP2PTransferEvents();
  initEqualizerEvents();
  initSheetControls();
  initSeekbarDragControls();
  
  await loadLibrarySongs();

  if (!allSongs || allSongs.length === 0) {
    await autoGenerateDemoTracks();
  } else {
    initDefaultPlayerUI();
  }

  await loadPlaylists();
});

function safeCreateObjectURL(blob, fallbackUrl = '') {
  if (!blob) return fallbackUrl;
  if (typeof blob === 'string') return blob;
  try {
    if (blob instanceof Blob || blob instanceof File) {
      return URL.createObjectURL(blob);
    }
  } catch (e) {
    console.warn("safeCreateObjectURL error:", e);
  }
  return fallbackUrl;
}

function initDefaultPlayerUI() {
  const current = playerEngine.getCurrentSong() || allSongs[0];
  if (current) {
    const cleanTitle = (current.title || '').replace(/\[e\]/gi, '').trim();
    const defaultArt = safeCreateObjectURL(current.coverBlob, getDefaultCoverUrl(cleanTitle, current.artist));
    document.getElementById('mini-art-img').src = defaultArt;
    document.getElementById('carousel-center').src = defaultArt;
    document.getElementById('carousel-left').src = defaultArt;
    document.getElementById('carousel-right').src = defaultArt;
    document.getElementById('mini-song-title').textContent = cleanTitle;
    document.getElementById('mini-song-artist').textContent = current.artist;
    document.getElementById('sheet-song-title').textContent = cleanTitle;
    document.getElementById('sheet-song-artist').textContent = current.artist;
    document.getElementById('mini-explicit-badge').style.display = current.explicit ? 'inline-block' : 'none';
    document.getElementById('sheet-explicit-badge').style.display = current.explicit ? 'inline-block' : 'none';
  }
  /* Keep mini player hidden until user taps play */
  hasUserPlayedAudio = false;
  const mini = document.getElementById('floating-mini-player');
  if (mini) {
    mini.style.display = 'none';
    mini.classList.remove('visible');
  }
}

/**
 * Generate cosmic planet SVG Data URL matching Nora Van Elken - This World artwork
 */
function getDefaultCoverUrl(title = 'This World', artist = 'Nora Van Elken') {
  const safeTitle = escapeHtml((title || '').replace(/\[e\]/gi, '').trim()).slice(0, 18);
  const safeArtist = escapeHtml(artist || '').slice(0, 20);
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='500' height='500' viewBox='0 0 500 500'>
    <defs>
      <radialGradient id='bgGrad' cx='50%' cy='50%' r='50%'>
        <stop offset='0%' stop-color='#ff2d55'/>
        <stop offset='50%' stop-color='#2b1055'/>
        <stop offset='100%' stop-color='#050507'/>
      </radialGradient>
      <radialGradient id='planetGrad' cx='35%' cy='35%' r='65%'>
        <stop offset='0%' stop-color='#a6c0fe'/>
        <stop offset='50%' stop-color='#37ecba'/>
        <stop offset='100%' stop-color='#050507'/>
      </radialGradient>
    </defs>
    <rect width='500' height='500' fill='url(#bgGrad)'/>
    <g stroke='rgba(255,255,255,0.22)' stroke-width='1.5'>
      <line x1='250' y1='30' x2='250' y2='470'/>
      <line x1='30' y1='250' x2='470' y2='250'/>
      <line x1='94' y1='94' x2='406' y2='406'/>
      <line x1='406' y1='94' x2='94' y2='406'/>
      <line x1='60' y1='170' x2='440' y2='330'/>
      <line x1='170' y1='60' x2='330' y2='440'/>
    </g>
    <circle cx='250' cy='250' r='105' fill='none' stroke='rgba(166,192,254,0.85)' stroke-width='4'/>
    <circle cx='250' cy='250' r='92' fill='url(#planetGrad)'/>
    <circle cx='250' cy='250' r='48' fill='#050507'/>
    <text x='250' y='425' fill='#ffffff' font-family='-apple-system, sans-serif' font-size='22' font-weight='bold' text-anchor='middle'>${safeTitle}</text>
    <text x='250' y='450' fill='rgba(255,255,255,0.65)' font-family='-apple-system, sans-serif' font-size='14' text-anchor='middle'>${safeArtist.toUpperCase()}</text>
  </svg>`;
  return 'data:image/svg+xml;utf8,' + encodeURIComponent(svg);
}

/* ==========================================================================
   Tab Navigation & Dock Switching
   ========================================================================== */
function initTabNavigation() {
  const dockItems = document.querySelectorAll('.dock-item');
  const tabViews = document.querySelectorAll('.tab-view');
  const heroOrb = document.getElementById('dock-hero-orb');
  const mainTitleEl = document.getElementById('page-main-title');
  const countEl = document.getElementById('library-count');

  const tabTitles = {
    'tab-library': 'Music Library',
    'tab-playlists': 'Playlists',
    'tab-transfer': 'Wi-Fi Import',
    'tab-settings': 'Equalizer'
  };

  dockItems.forEach((item) => {
    item.addEventListener('click', () => {
      closeNowPlayingSheet();

      const targetTabId = item.dataset.tab;

      dockItems.forEach((d) => d.classList.remove('active'));
      item.classList.add('active');

      tabViews.forEach((view) => {
        if (view.id === targetTabId) {
          view.classList.add('active');
        } else {
          view.classList.remove('active');
        }
      });

      if (mainTitleEl && tabTitles[targetTabId]) {
        mainTitleEl.textContent = tabTitles[targetTabId];
      }
      if (countEl) {
        countEl.style.display = (targetTabId === 'tab-library') ? 'inline-block' : 'none';
      }
    });
  });

  /* Center Orb Two-Way Toggle Control */
  heroOrb.addEventListener('click', () => {
    const sheet = document.getElementById('now-playing-sheet');
    if (sheet.classList.contains('open')) {
      closeNowPlayingSheet();
    } else {
      openNowPlayingSheet();
    }
  });

  document.getElementById('btn-open-now-playing-sheet').addEventListener('click', () => {
    openNowPlayingSheet();
  });
}

/* ==========================================================================
   Library & Song Loading + Multi-Select Delete
   ========================================================================== */
async function loadLibrarySongs() {
  try {
    allSongs = await musicStorage.getAllSongs();
    applyFilterAndSearch();
  } catch (e) {
    console.error("Failed to load songs from IndexedDB:", e);
  }
}

function applyFilterAndSearch() {
  filteredSongs = allSongs.filter((song) => {
    const matchesSearch = searchQuery === '' || 
      song.title.toLowerCase().includes(searchQuery) ||
      song.artist.toLowerCase().includes(searchQuery) ||
      song.album.toLowerCase().includes(searchQuery);

    if (!matchesSearch) return false;

    if (currentFilter === 'favorites') return song.isFavorite;
    return true;
  });

  renderLibrarySongs();
}

function renderLibrarySongs() {
  const listContainer = document.getElementById('library-song-list');
  const emptyView = document.getElementById('library-empty');
  const countLabel = document.getElementById('library-count');

  countLabel.textContent = `${filteredSongs.length} Songs`;

  if (filteredSongs.length === 0) {
    listContainer.innerHTML = '';
    emptyView.style.display = 'block';
    return;
  }

  emptyView.style.display = 'none';
  const currentSong = playerEngine.getCurrentSong();

  listContainer.innerHTML = filteredSongs.map((song, index) => {
    const isPlaying = currentSong && currentSong.id === song.id;
    const cleanTitle = (song.title || '').replace(/\[e\]/gi, '').trim();
    const coverSrc = safeCreateObjectURL(song.coverBlob, getDefaultCoverUrl(cleanTitle, song.artist));
    const isChecked = selectedMultiSongIds.has(song.id);

    return `
      <div class="song-card ${isPlaying ? 'playing' : ''} ${isMultiSelectMode ? 'multi-selecting' : ''}" data-id="${song.id}" data-index="${index}">
        ${isMultiSelectMode ? `<input type="checkbox" class="song-card-checkbox" ${isChecked ? 'checked' : ''} data-song-id="${song.id}">` : ''}
        <div class="song-art-wrapper">
          <img src="${coverSrc}" class="song-art" alt="" onerror="this.src='${getDefaultCoverUrl()}'">
          <div class="soundwave-overlay">
            <div class="wave-bar"></div>
            <div class="wave-bar"></div>
            <div class="wave-bar"></div>
          </div>
        </div>
        <div class="song-info">
          <div class="song-title-row">
            <span class="song-title">${escapeHtml(cleanTitle)}</span>
            ${song.explicit ? '<span class="explicit-badge">E</span>' : ''}
          </div>
          <div class="song-subtext">${escapeHtml(song.artist)}</div>
        </div>
        <div class="song-actions">
          <span style="font-size: 12px; color: var(--text-muted); font-family: monospace; margin-right: 4px;">${formatTime(song.duration)}</span>
          ${!isMultiSelectMode ? `
            <button class="action-btn favorite ${song.isFavorite ? 'active' : ''}" data-action="favorite" data-id="${song.id}">
              ${song.isFavorite ? '♥' : '♡'}
            </button>
            <button class="action-btn" data-action="delete" data-id="${song.id}">🗑️</button>
          ` : ''}
        </div>
      </div>
    `;
  }).join('');

  const songCards = listContainer.querySelectorAll('.song-card');

  songCards.forEach((card) => {
    const songId = card.dataset.id;
    const index = parseInt(card.dataset.index, 10);

    /* Touch & Mouse Long-Press Handlers (500ms) */
    const startPress = () => {
      longPressTimer = setTimeout(() => {
        if (!isMultiSelectMode) {
          isMultiSelectMode = true;
          selectedMultiSongIds.clear();
          selectedMultiSongIds.add(songId);
          updateMultiSelectUI();
          renderLibrarySongs();
        }
      }, 500);
    };

    const cancelPress = () => {
      if (longPressTimer) {
        clearTimeout(longPressTimer);
        longPressTimer = null;
      }
    };

    card.addEventListener('mousedown', startPress);
    card.addEventListener('mouseup', cancelPress);
    card.addEventListener('mouseleave', cancelPress);
    card.addEventListener('touchstart', startPress, { passive: true });
    card.addEventListener('touchend', cancelPress);
    card.addEventListener('touchmove', cancelPress);

    card.addEventListener('click', (e) => {
      if (e.target.closest('.action-btn')) return;

      if (isMultiSelectMode) {
        if (selectedMultiSongIds.has(songId)) {
          selectedMultiSongIds.delete(songId);
        } else {
          selectedMultiSongIds.add(songId);
        }
        updateMultiSelectUI();
        renderLibrarySongs();
      } else {
        hasUserPlayedAudio = true;
        currentSourcePlaylistName = null;
        playerEngine.setQueue(filteredSongs, index);
        playerEngine.play();
        showMiniPlayer();
      }
    });
  });

  listContainer.querySelectorAll('[data-action="favorite"]').forEach((btn) => {
    btn.addEventListener('click', async (e) => {
      e.stopPropagation();
      const songId = btn.dataset.id;
      const isFav = await musicStorage.toggleFavorite(songId);
      const songObj = allSongs.find((s) => s.id === songId);
      if (songObj) songObj.isFavorite = isFav;
      applyFilterAndSearch();
      await renderPlaylists();
    });
  });

  listContainer.querySelectorAll('[data-action="delete"]').forEach((btn) => {
    btn.addEventListener('click', async (e) => {
      e.stopPropagation();
      const songId = btn.dataset.id;
      if (confirm("Delete this song from offline storage?")) {
        await musicStorage.deleteSong(songId);
        await loadLibrarySongs();
        await renderPlaylists();
      }
    });
  });
}

function updateMultiSelectUI() {
  const bar = document.getElementById('library-multi-select-bar');
  const countLabel = document.getElementById('multi-select-count');

  if (isMultiSelectMode) {
    bar.style.display = 'flex';
    countLabel.textContent = `${selectedMultiSongIds.size} Terpilih`;
  } else {
    bar.style.display = 'none';
  }
}

function updatePlayingSongStateUI() {
  const currentSong = playerEngine.getCurrentSong();
  const currentId = currentSong ? currentSong.id : null;
  const isPlaying = playerEngine.isPlaying;

  document.querySelectorAll('#library-song-list .song-card').forEach(card => {
    const isThisCard = card.dataset.id === currentId;
    card.classList.toggle('playing', isThisCard && isPlaying);
  });

  document.querySelectorAll('.queue-track-row').forEach(row => {
    const songId = row.dataset.songId;
    const isThisRow = songId === currentId;
    row.classList.toggle('active', isThisRow);
  });
}

function initLibraryEvents() {
  const searchInput = document.getElementById('search-library-input');
  searchInput.addEventListener('input', (e) => {
    searchQuery = e.target.value.trim().toLowerCase();
    applyFilterAndSearch();
  });

  const filterChips = document.querySelectorAll('.filter-chips .chip');
  filterChips.forEach((chip) => {
    chip.addEventListener('click', () => {
      filterChips.forEach((c) => c.classList.remove('active'));
      chip.classList.add('active');
      currentFilter = chip.dataset.filter || 'all';
      applyFilterAndSearch();
    });
  });

  const btnCancelMulti = document.getElementById('btn-cancel-multi-select');
  const btnSelectAll = document.getElementById('btn-select-all-library');
  const btnDeleteSelected = document.getElementById('btn-delete-selected-library');

  btnCancelMulti.addEventListener('click', () => {
    isMultiSelectMode = false;
    selectedMultiSongIds.clear();
    updateMultiSelectUI();
    renderLibrarySongs();
  });

  btnSelectAll.addEventListener('click', () => {
    if (selectedMultiSongIds.size === filteredSongs.length) {
      selectedMultiSongIds.clear();
    } else {
      filteredSongs.forEach(s => selectedMultiSongIds.add(s.id));
    }
    updateMultiSelectUI();
    renderLibrarySongs();
  });

  btnDeleteSelected.addEventListener('click', async () => {
    if (selectedMultiSongIds.size === 0) return;
    if (confirm(`Hapus ${selectedMultiSongIds.size} lagu terpilih secara permanen?`)) {
      for (const id of selectedMultiSongIds) {
        await musicStorage.deleteSong(id);
      }
      isMultiSelectMode = false;
      selectedMultiSongIds.clear();
      updateMultiSelectUI();
      await loadLibrarySongs();
      await renderPlaylists();
    }
  });

  const fileInput = document.getElementById('file-input');
  document.getElementById('btn-open-file-input').addEventListener('click', () => fileInput.click());

  fileInput.addEventListener('change', async (e) => {
    const files = Array.from(e.target.files);
    if (files.length === 0) return;

    for (const file of files) {
      const songData = await extractMetadata(file);
      await musicStorage.saveSong(songData);
    }
    await loadLibrarySongs();
    alert(`Successfully imported ${files.length} song(s) into offline library!`);
  });

  const btnDemo = document.getElementById('btn-generate-demo');
  if (btnDemo) {
    btnDemo.addEventListener('click', async () => {
      await autoGenerateDemoTracks();
    });
  }

  document.getElementById('btn-empty-import').addEventListener('click', async () => {
    fileInput.click();
  });
}

async function autoGenerateDemoTracks() {
  const demos = await generateDemoTracks();
  await musicStorage.saveSongsBatch(demos);
  await loadLibrarySongs();
  currentSourcePlaylistName = "Energetic music";
  initDefaultPlayerUI();
  await renderPlaylists();
}

/* ==========================================================================
   Playlists Management & 1:1 Apple Music iOS Create / Detail Layout
   ========================================================================== */
async function loadPlaylists() {
  allPlaylists = await musicStorage.getAllPlaylists();
  renderPlaylists();
}

function renderPlaylists() {
  const container = document.getElementById('playlists-list');

  const favorites = allSongs.filter(s => s.isFavorite);

  let html = `
    <div class="song-card" data-playlist-type="favorites">
      <div class="song-art-wrapper" style="background: linear-gradient(135deg, var(--accent-pink), var(--accent-indigo)); display: flex; align-items: center; justify-content: center; font-size: 24px; color: #fff;">
        ♥
      </div>
      <div class="song-info">
        <div class="song-title">Favorites</div>
        <div class="song-subtext">${favorites.length} Songs</div>
      </div>
      <div class="song-actions">
        <button class="action-btn">▶</button>
      </div>
    </div>
  `;

  allPlaylists.forEach((pl) => {
    const songCount = (pl.songIds || []).length;
    const coverSrc = safeCreateObjectURL(pl.coverBlob, getDefaultCoverUrl(pl.name, `${songCount} Songs`));

    html += `
      <div class="song-card" data-playlist-id="${pl.id}">
        <div class="song-art-wrapper">
          <img src="${coverSrc}" class="song-art" alt="" onerror="this.src='${getDefaultCoverUrl()}'">
        </div>
        <div class="song-info">
          <div class="song-title">${escapeHtml(pl.name)}</div>
          <div class="song-subtext">${songCount} Tracks</div>
        </div>
        <div class="song-actions">
          <button class="action-btn" data-action="play-playlist" data-id="${pl.id}">▶</button>
          <button class="action-btn" data-action="delete-playlist" data-id="${pl.id}">🗑️</button>
        </div>
      </div>
    `;
  });

  container.innerHTML = html;

  container.querySelectorAll('[data-playlist-type="favorites"]').forEach(card => {
    card.addEventListener('click', () => openFullPagePlaylistDetail('favorites'));
  });

  container.querySelectorAll('[data-playlist-id]').forEach(card => {
    card.addEventListener('click', (e) => {
      if (e.target.closest('[data-action="delete-playlist"]')) return;
      const plId = card.dataset.playlistId;
      openFullPagePlaylistDetail(plId);
    });
  });

  container.querySelectorAll('[data-action="delete-playlist"]').forEach(btn => {
    btn.addEventListener('click', async (e) => {
      e.stopPropagation();
      const plId = btn.dataset.id;
      if (confirm("Hapus playlist ini?")) {
        await musicStorage.deletePlaylist(plId);
        await loadPlaylists();
      }
    });
  });
}

function openFullPagePlaylistDetail(playlistId) {
  const mainView = document.getElementById('playlists-main-view');
  const fullView = document.getElementById('playlists-detail-fullview');
  const countLabel = document.getElementById('detail-fullview-count');
  const titleLabel = document.getElementById('detail-fullview-title');
  const artImg = document.getElementById('detail-fullview-art');
  const listContainer = document.getElementById('detail-fullview-song-list');
  const btnPlayAll = document.getElementById('btn-play-all-fullview');
  const btnBack = document.getElementById('btn-back-playlist-detail');

  let playlistSongs = [];
  let playlistTitle = "";

  if (playlistId === 'favorites') {
    playlistTitle = "Favorites";
    playlistSongs = allSongs.filter(s => s.isFavorite);
    artImg.src = getDefaultCoverUrl("Favorites", `${playlistSongs.length} Songs`);
    currentActivePlaylistDetail = { id: 'favorites', songs: playlistSongs };
  } else {
    const pl = allPlaylists.find(p => p.id === playlistId);
    if (!pl) return;
    playlistTitle = pl.name;
    playlistSongs = allSongs.filter(s => (pl.songIds || []).includes(s.id));
    artImg.src = safeCreateObjectURL(pl.coverBlob, getDefaultCoverUrl(pl.name, `${playlistSongs.length} Songs`));
    currentActivePlaylistDetail = pl;
  }

  titleLabel.textContent = playlistTitle;
  countLabel.textContent = `${playlistSongs.length} Tracks`;

  if (playlistSongs.length === 0) {
    listContainer.innerHTML = `<div style="text-align: center; color: var(--text-muted); padding: 30px; font-size: 14px;">Playlist ini masih kosong.</div>`;
  } else {
    listContainer.innerHTML = playlistSongs.map((song, idx) => {
      const cleanTitle = (song.title || '').replace(/\[e\]/gi, '').trim();
      const coverSrc = safeCreateObjectURL(song.coverBlob, getDefaultCoverUrl(cleanTitle, song.artist));
      return `
        <div class="song-card" data-detail-song-index="${idx}">
          <div class="song-art-wrapper">
            <img src="${coverSrc}" class="song-art" alt="">
          </div>
          <div class="song-info">
            <div class="song-title-row">
              <span class="song-title">${escapeHtml(cleanTitle)}</span>
              ${song.explicit ? '<span class="explicit-badge">E</span>' : ''}
            </div>
            <div class="song-subtext">${escapeHtml(song.artist)}</div>
          </div>
          <div class="song-actions">
            <span style="font-size: 12px; color: var(--text-muted); font-family: monospace;">${formatTime(song.duration)}</span>
            ${playlistId !== 'favorites' ? `<button class="action-btn" data-action="remove-from-playlist" data-song-id="${song.id}">🗑️</button>` : ''}
          </div>
        </div>
      `;
    }).join('');

    listContainer.querySelectorAll('.song-card').forEach(card => {
      card.addEventListener('click', (e) => {
        if (e.target.closest('[data-action="remove-from-playlist"]')) return;
        const idx = parseInt(card.dataset.detailSongIndex, 10);
        hasUserPlayedAudio = true;
        currentSourcePlaylistName = playlistTitle;
        playerEngine.setQueue(playlistSongs, idx);
        playerEngine.play();
        showMiniPlayer();
      });
    });

    listContainer.querySelectorAll('[data-action="remove-from-playlist"]').forEach(btn => {
      btn.addEventListener('click', async (e) => {
        e.stopPropagation();
        const songId = btn.dataset.songId;
        if (currentActivePlaylistDetail && currentActivePlaylistDetail.id !== 'favorites') {
          currentActivePlaylistDetail.songIds = currentActivePlaylistDetail.songIds.filter(id => id !== songId);
          await musicStorage.savePlaylist(currentActivePlaylistDetail);
          await loadPlaylists();
          openFullPagePlaylistDetail(currentActivePlaylistDetail.id);
        }
      });
    });
  }

  btnPlayAll.onclick = () => {
    if (playlistSongs.length === 0) return;
    hasUserPlayedAudio = true;
    currentSourcePlaylistName = playlistTitle;
    playerEngine.setQueue(playlistSongs, 0);
    playerEngine.play();
    showMiniPlayer();
  };

  btnBack.onclick = () => {
    fullView.style.display = 'none';
    mainView.style.display = 'block';
  };

  mainView.style.display = 'none';
  fullView.style.display = 'block';
}

function initPlaylistModalEvents() {
  const modal = document.getElementById('modal-create-playlist');
  const btnCreate = document.getElementById('btn-create-playlist');
  const btnCancel = document.getElementById('btn-cancel-playlist');
  const btnSave = document.getElementById('btn-save-playlist');
  const trackChecklist = document.getElementById('playlist-track-checklist');
  const nameInput = document.getElementById('playlist-name-input');
  const headerTitle = document.getElementById('create-playlist-header-title');
  const btnAddMusic = document.getElementById('btn-trigger-add-music');
  const selectedPreview = document.getElementById('create-selected-songs-preview');
  const coverPicker = document.getElementById('playlist-cover-picker');
  const coverTrigger = document.getElementById('btn-trigger-cover-picker');

  btnCreate.addEventListener('click', () => {
    if (allSongs.length === 0) {
      alert("Library masih kosong. Impor lagu terlebih dahulu.");
      return;
    }

    selectedSongIdsForPlaylist.clear();
    selectedCoverBlobForPlaylist = null;
    nameInput.value = 'Untitled Playlist';
    headerTitle.textContent = 'Untitled Playlist';
    trackChecklist.style.display = 'none';
    coverPicker.style.display = 'none';

    renderPlaylistCreateTracklist();
    updateCreatePlaylistCoverArt();
    modal.classList.add('open');
  });

  nameInput.addEventListener('input', (e) => {
    const val = e.target.value.trim() || 'Untitled Playlist';
    headerTitle.textContent = val;
  });

  btnAddMusic.addEventListener('click', () => {
    const isHidden = trackChecklist.style.display === 'none';
    trackChecklist.style.display = isHidden ? 'flex' : 'none';
  });

  coverTrigger.addEventListener('click', () => {
    const isHidden = coverPicker.style.display === 'none';
    coverPicker.style.display = isHidden ? 'flex' : 'none';
  });

  const closeModal = () => { modal.classList.remove('open'); };
  btnCancel.addEventListener('click', closeModal);

  btnSave.addEventListener('click', async () => {
    const name = nameInput.value.trim() || 'Untitled Playlist';
    if (selectedSongIdsForPlaylist.size === 0) {
      alert("Pilih minimal 1 lagu dengan menekan 'Add Music...'!");
      return;
    }

    if (!selectedCoverBlobForPlaylist) {
      const firstSongId = Array.from(selectedSongIdsForPlaylist)[0];
      const firstSong = allSongs.find(s => s.id === firstSongId);
      if (firstSong) selectedCoverBlobForPlaylist = firstSong.coverBlob || null;
    }

    const newPlaylist = {
      id: 'pl_' + Date.now(),
      name,
      songIds: Array.from(selectedSongIdsForPlaylist),
      coverBlob: selectedCoverBlobForPlaylist,
      createdAt: Date.now(),
    };

    await musicStorage.savePlaylist(newPlaylist);
    closeModal();
    await loadPlaylists();
    alert(`Playlist "${name}" berhasil dibuat!`);
  });
}

function renderPlaylistCreateTracklist() {
  const trackChecklist = document.getElementById('playlist-track-checklist');
  const selectedPreview = document.getElementById('create-selected-songs-preview');

  trackChecklist.innerHTML = allSongs.map(song => {
    const cleanTitle = (song.title || '').replace(/\[e\]/gi, '').trim();
    const coverSrc = safeCreateObjectURL(song.coverBlob, getDefaultCoverUrl(cleanTitle, song.artist));
    const isChecked = selectedSongIdsForPlaylist.has(song.id);

    return `
      <label class="track-check-row">
        <input type="checkbox" value="${song.id}" class="playlist-song-checkbox" ${isChecked ? 'checked' : ''}>
        <img src="${coverSrc}" style="width: 36px; height: 36px; border-radius: 8px; object-fit: cover;" alt="">
        <div style="flex: 1; min-width: 0;">
          <div style="font-size: 14px; font-weight: 600; text-overflow: ellipsis; overflow: hidden; white-space: nowrap;">${escapeHtml(cleanTitle)}</div>
          <div style="font-size: 12px; color: var(--text-muted); text-overflow: ellipsis; overflow: hidden; white-space: nowrap;">${escapeHtml(song.artist)}</div>
        </div>
      </label>
    `;
  }).join('');

  trackChecklist.querySelectorAll('.playlist-song-checkbox').forEach(cb => {
    cb.addEventListener('change', (e) => {
      const songId = e.target.value;
      if (e.target.checked) {
        selectedSongIdsForPlaylist.add(songId);
      } else {
        selectedSongIdsForPlaylist.delete(songId);
      }
      renderSelectedPreview();
      updatePlaylistCoverPicker();
      updateCreatePlaylistCoverArt();
    });
  });

  renderSelectedPreview();
  updatePlaylistCoverPicker();
}

function renderSelectedPreview() {
  const selectedPreview = document.getElementById('create-selected-songs-preview');
  const selectedSongs = allSongs.filter(s => selectedSongIdsForPlaylist.has(s.id));

  selectedPreview.innerHTML = selectedSongs.map(song => {
    const cleanTitle = (song.title || '').replace(/\[e\]/gi, '').trim();
    const coverSrc = safeCreateObjectURL(song.coverBlob, getDefaultCoverUrl(cleanTitle, song.artist));

    return `
      <div class="song-card" style="padding: 8px 10px;">
        <img src="${coverSrc}" style="width: 40px; height: 40px; border-radius: 10px; object-fit: cover;">
        <div class="song-info">
          <div class="song-title">${escapeHtml(cleanTitle)}</div>
          <div class="song-subtext">${escapeHtml(song.artist)}</div>
        </div>
        <button class="action-btn" data-remove-id="${song.id}">🗑️</button>
      </div>
    `;
  }).join('');

  selectedPreview.querySelectorAll('[data-remove-id]').forEach(btn => {
    btn.addEventListener('click', () => {
      const id = btn.dataset.removeId;
      selectedSongIdsForPlaylist.delete(id);
      renderPlaylistCreateTracklist();
    });
  });
}

function updateCreatePlaylistCoverArt() {
  const coverImg = document.getElementById('create-playlist-cover-img');
  const artPlaceholder = document.getElementById('create-playlist-art-placeholder');
  const selectedSongs = allSongs.filter(s => selectedSongIdsForPlaylist.has(s.id));

  const chosenBlob = selectedCoverBlobForPlaylist || (selectedSongs.length > 0 ? selectedSongs[0].coverBlob : null);
  const coverSrc = safeCreateObjectURL(chosenBlob, '');

  if (coverSrc) {
    coverImg.src = coverSrc;
    coverImg.style.display = 'block';
    artPlaceholder.style.display = 'none';
  } else {
    coverImg.style.display = 'none';
    artPlaceholder.style.display = 'flex';
  }
}

function updatePlaylistCoverPicker() {
  const coverPicker = document.getElementById('playlist-cover-picker');
  const selectedSongs = allSongs.filter(s => selectedSongIdsForPlaylist.has(s.id));

  if (selectedSongs.length === 0) {
    coverPicker.innerHTML = `<div style="font-size: 12px; color: var(--text-muted);">Pilih lagu melalui 'Add Music...' untuk opsi sampul.</div>`;
    return;
  }

  coverPicker.innerHTML = selectedSongs.map((song, idx) => {
    const cleanTitle = (song.title || '').replace(/\[e\]/gi, '').trim();
    const coverSrc = safeCreateObjectURL(song.coverBlob, getDefaultCoverUrl(cleanTitle, song.artist));
    const isSelected = (selectedCoverBlobForPlaylist === song.coverBlob) || (idx === 0 && !selectedCoverBlobForPlaylist);
    return `
      <img src="${coverSrc}" class="cover-option-thumb ${isSelected ? 'selected' : ''}" data-index="${idx}" alt="">
    `;
  }).join('');

  coverPicker.querySelectorAll('.cover-option-thumb').forEach((thumb) => {
    thumb.addEventListener('click', () => {
      const idx = parseInt(thumb.dataset.index, 10);
      const chosenSong = selectedSongs[idx];
      selectedCoverBlobForPlaylist = chosenSong ? chosenSong.coverBlob : null;

      coverPicker.querySelectorAll('.cover-option-thumb').forEach(t => t.classList.remove('selected'));
      thumb.classList.add('selected');
      updateCreatePlaylistCoverArt();
    });
  });
}

/* ==========================================================================
   Player Engine & UI Sync
   ========================================================================== */
function initPlayerEvents() {
  const miniPlayer = document.getElementById('floating-mini-player');
  const miniArt = document.getElementById('mini-art-img');
  const miniTitle = document.getElementById('mini-song-title');
  const miniArtist = document.getElementById('mini-song-artist');
  const miniExplicit = document.getElementById('mini-explicit-badge');
  const miniBtnPrev = document.getElementById('mini-btn-prev');
  const miniBtnPlay = document.getElementById('mini-btn-play');
  const miniBtnNext = document.getElementById('mini-btn-next');

  miniPlayer.addEventListener('click', (e) => {
    if (e.target.closest('.action-btn')) return;
    openNowPlayingSheet();
  });

  if (miniBtnPrev) {
    miniBtnPrev.addEventListener('click', (e) => {
      e.stopPropagation();
      hasUserPlayedAudio = true;
      playerEngine.prev();
    });
  }

  if (miniBtnPlay) {
    miniBtnPlay.addEventListener('click', (e) => {
      e.stopPropagation();
      hasUserPlayedAudio = true;
      playerEngine.togglePlay();
    });
  }

  if (miniBtnNext) {
    miniBtnNext.addEventListener('click', (e) => {
      e.stopPropagation();
      hasUserPlayedAudio = true;
      playerEngine.next();
    });
  }

  playerEngine.onTrackChange = (song, coverUrl, index) => {
    if (!song) return;

    const cleanTitle = (song.title || '').replace(/\[e\]/gi, '').trim();

    miniTitle.textContent = cleanTitle;
    miniArtist.textContent = song.artist;
    miniExplicit.style.display = song.explicit ? 'inline-block' : 'none';
    miniArt.src = coverUrl || getDefaultCoverUrl(cleanTitle, song.artist);

    updateSheetTrackInfo(song, coverUrl, index);
    renderSheetQueueTracklist();
    updatePlayingSongStateUI();

    if (hasUserPlayedAudio) {
      showMiniPlayer();
    }
  };

  playerEngine.onPlayStateChange = (isPlaying) => {
    if (miniBtnPlay) {
      miniBtnPlay.innerHTML = isPlaying 
        ? '<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"/></svg>'
        : '<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg>';
    }
    const playSvg = document.getElementById('sheet-play-svg-icon');
    if (playSvg) {
      playSvg.innerHTML = isPlaying ? '<path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"/>' : '<path d="M8 5v14l11-7z"/>';
    }
    updatePlayingSongStateUI();

    if (isPlaying) {
      hasUserPlayedAudio = true;
      showMiniPlayer();
    }
  };

  playerEngine.onTimeUpdate = (currentTime, duration) => {
    if (isDraggingSeekbar) return;

    const timeElapsed = document.getElementById('time-elapsed');
    const timeRemaining = document.getElementById('time-remaining');
    const fill = document.getElementById('seekbar-fill');
    const thumb = document.getElementById('seekbar-thumb');

    timeElapsed.textContent = formatTime(currentTime);
    const rem = duration - currentTime;
    timeRemaining.textContent = isNaN(rem) ? '-0:00' : `-${formatTime(rem)}`;

    const percent = duration > 0 ? (currentTime / duration) * 100 : 0;
    fill.style.width = `${percent}%`;
    thumb.style.left = `${percent}%`;
  };

  playerEngine.onQueueChange = () => {
    renderSheetQueueTracklist();
  };
}

/* ==========================================================================
   Seekbar Drag Controls
   ========================================================================== */
function initSeekbarDragControls() {
  const track = document.getElementById('seekbar-track');
  const fill = document.getElementById('seekbar-fill');
  const thumb = document.getElementById('seekbar-thumb');
  const timeElapsed = document.getElementById('time-elapsed');

  let dragPercent = 0;

  const updateSeekPosFromEvent = (e) => {
    const rect = track.getBoundingClientRect();
    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    const clickX = clientX - rect.left;
    dragPercent = Math.max(0, Math.min(1, clickX / rect.width));

    fill.style.width = `${dragPercent * 100}%`;
    thumb.style.left = `${dragPercent * 100}%`;

    if (playerEngine.audio.duration) {
      const seekSec = dragPercent * playerEngine.audio.duration;
      timeElapsed.textContent = formatTime(seekSec);
    }
  };

  const startDrag = (e) => {
    isDraggingSeekbar = true;
    thumb.classList.add('dragging');
    updateSeekPosFromEvent(e);
  };

  const moveDrag = (e) => {
    if (!isDraggingSeekbar) return;
    updateSeekPosFromEvent(e);
  };

  const stopDrag = () => {
    if (!isDraggingSeekbar) return;
    isDraggingSeekbar = false;
    thumb.classList.remove('dragging');
    if (playerEngine.audio.duration) {
      playerEngine.seek(dragPercent * playerEngine.audio.duration);
    }
  };

  track.addEventListener('mousedown', startDrag);
  window.addEventListener('mousemove', moveDrag);
  window.addEventListener('mouseup', stopDrag);

  track.addEventListener('touchstart', startDrag, { passive: true });
  window.addEventListener('touchmove', moveDrag, { passive: true });
  window.addEventListener('touchend', stopDrag);
}

function showMiniPlayer() {
  if (!hasUserPlayedAudio) return; // Keep hidden until user plays music!

  const mini = document.getElementById('floating-mini-player');
  const sheet = document.getElementById('now-playing-sheet');

  if (mini && !sheet.classList.contains('open') && (playerEngine.getCurrentSong() || allSongs.length > 0)) {
    mini.style.display = 'flex';
    requestAnimationFrame(() => {
      mini.classList.add('visible');
    });
  }
}

/* ==========================================================================
   Now Playing Full-Screen Sheet Controls & Volume Slider
   ========================================================================== */
function initSheetControls() {
  const btnClose = document.getElementById('btn-close-sheet');
  const sheetDragHandle = document.getElementById('sheet-close-handle');
  const btnPlay = document.getElementById('sheet-btn-play');
  const btnPrev = document.getElementById('sheet-btn-prev');
  const btnNext = document.getElementById('sheet-btn-next');
  const btnRepeat = document.getElementById('sheet-btn-repeat');
  const btnShuffle = document.getElementById('sheet-btn-shuffle');
  const btnFavorite = document.getElementById('sheet-btn-favorite');
  const btnToggleEq = document.getElementById('btn-toggle-eq-panel');
  const sheetEqPanel = document.getElementById('sheet-eq-panel');
  const btnSheetQueue = document.getElementById('btn-sheet-queue');
  const carouselWrapper = document.getElementById('carousel-view-wrapper');
  const queueWrapper = document.getElementById('queue-view-wrapper');
  const volumeSlider = document.getElementById('sheet-volume-slider');

  if (btnClose) btnClose.addEventListener('click', () => closeNowPlayingSheet());
  if (sheetDragHandle) sheetDragHandle.addEventListener('click', () => closeNowPlayingSheet());

  if (volumeSlider) {
    volumeSlider.addEventListener('input', (e) => {
      const vol = parseFloat(e.target.value);
      playerEngine.setVolume(vol);
    });
  }

  if (btnToggleEq && sheetEqPanel) {
    btnToggleEq.addEventListener('click', () => {
      const isHidden = sheetEqPanel.style.display === 'none';
      sheetEqPanel.style.display = isHidden ? 'block' : 'none';
      btnToggleEq.classList.toggle('active', isHidden);
    });
  }

  if (btnSheetQueue && carouselWrapper && queueWrapper) {
    btnSheetQueue.addEventListener('click', () => {
      if (sheetViewMode === 'carousel') {
        sheetViewMode = 'queue';
        carouselWrapper.style.display = 'none';
        queueWrapper.style.display = 'block';
        btnSheetQueue.classList.add('active');
        renderSheetQueueTracklist();
      } else {
        sheetViewMode = 'carousel';
        carouselWrapper.style.display = 'block';
        queueWrapper.style.display = 'none';
        btnSheetQueue.classList.remove('active');
      }
    });
  }

  if (btnPlay) {
    btnPlay.addEventListener('click', () => {
      hasUserPlayedAudio = true;
      playerEngine.togglePlay();
    });
  }

  if (btnPrev) {
    btnPrev.addEventListener('click', () => {
      hasUserPlayedAudio = true;
      playerEngine.prev();
    });
  }

  if (btnNext) {
    btnNext.addEventListener('click', () => {
      hasUserPlayedAudio = true;
      playerEngine.next();
    });
  }

  if (btnRepeat) {
    btnRepeat.addEventListener('click', () => {
      const mode = playerEngine.toggleRepeatMode();
      btnRepeat.classList.toggle('active', mode !== 'off');
    });
  }

  if (btnShuffle) {
    btnShuffle.addEventListener('click', () => {
      const isShuffle = playerEngine.toggleShuffle();
      btnShuffle.classList.toggle('active', isShuffle);
    });
  }

  if (btnFavorite) {
    btnFavorite.addEventListener('click', async () => {
      const current = playerEngine.getCurrentSong();
      if (!current) return;
      const isFav = await musicStorage.toggleFavorite(current.id);
      current.isFavorite = isFav;
      btnFavorite.textContent = isFav ? '♥' : '♡';
      btnFavorite.classList.toggle('active', isFav);
      await loadLibrarySongs();
      await renderPlaylists();
    });
  }
}

function openNowPlayingSheet() {
  if (!playerEngine.getCurrentSong() && allSongs.length > 0) {
    playerEngine.setQueue(allSongs, 0);
  }
  const mini = document.getElementById('floating-mini-player');
  if (mini) {
    mini.classList.remove('visible');
    setTimeout(() => { mini.style.display = 'none'; }, 200);
  }
  document.getElementById('now-playing-sheet').classList.add('open');
}

function closeNowPlayingSheet() {
  document.getElementById('now-playing-sheet').classList.remove('open');
  if (hasUserPlayedAudio) {
    showMiniPlayer();
  }
}

function updateSheetTrackInfo(song, coverUrl, index) {
  const cleanTitle = (song.title || '').replace(/\[e\]/gi, '').trim();

  document.getElementById('sheet-song-title').textContent = cleanTitle;
  document.getElementById('sheet-song-artist').textContent = song.artist;
  document.getElementById('sheet-explicit-badge').style.display = song.explicit ? 'inline-block' : 'none';

  const headerPlaylist = document.getElementById('sheet-header-playlist');
  const headerSubtitle = document.getElementById('sheet-header-subtitle');
  if (currentSourcePlaylistName) {
    headerPlaylist.textContent = currentSourcePlaylistName;
    headerSubtitle.textContent = "PLAYLIST";
  } else {
    headerPlaylist.textContent = "Anywhere Player";
    headerSubtitle.textContent = "NOW PLAYING";
  }

  const favBtn = document.getElementById('sheet-btn-favorite');
  favBtn.textContent = song.isFavorite ? '♥' : '♡';
  favBtn.classList.toggle('active', song.isFavorite);

  const imgCenter = document.getElementById('carousel-center');
  const imgLeft = document.getElementById('carousel-left');
  const imgRight = document.getElementById('carousel-right');

  const mainCover = coverUrl || getDefaultCoverUrl(cleanTitle, song.artist);
  imgCenter.src = mainCover;

  const prevSong = playerEngine.queue[index - 1] || playerEngine.queue[playerEngine.queue.length - 1];
  const prevClean = prevSong ? (prevSong.title || '').replace(/\[e\]/gi, '').trim() : '';
  imgLeft.src = safeCreateObjectURL(prevSong?.coverBlob, getDefaultCoverUrl(prevClean, ''));

  const nextSong = playerEngine.queue[index + 1] || playerEngine.queue[0];
  const nextClean = nextSong ? (nextSong.title || '').replace(/\[e\]/gi, '').trim() : '';
  imgRight.src = safeCreateObjectURL(nextSong?.coverBlob, getDefaultCoverUrl(nextClean, ''));
}

function renderSheetQueueTracklist() {
  const container = document.getElementById('sheet-queue-song-list');
  if (!container) return;

  const queue = playerEngine.queue.length > 0 ? playerEngine.queue : allSongs;
  const currentSong = playerEngine.getCurrentSong();

  if (!queue || queue.length === 0) {
    container.innerHTML = `<div style="font-size: 13px; color: var(--text-muted); padding: 20px; text-align: center;">Antrean kosong</div>`;
    return;
  }

  container.innerHTML = queue.map((song, idx) => {
    const isCurrent = currentSong && currentSong.id === song.id;
    const cleanTitle = (song.title || '').replace(/\[e\]/gi, '').trim();
    const coverSrc = safeCreateObjectURL(song.coverBlob, getDefaultCoverUrl(cleanTitle, song.artist));

    return `
      <div class="queue-track-row ${isCurrent ? 'active' : ''}" data-queue-index="${idx}" data-song-id="${song.id}">
        <div style="position: relative; width: 42px; height: 42px; border-radius: 10px; overflow: hidden; flex-shrink: 0;">
          <img src="${coverSrc}" style="width: 100%; height: 100%; object-fit: cover;" alt="">
          ${isCurrent ? `
            <div style="position: absolute; top:0; left:0; width:100%; height:100%; background: rgba(5,5,7,0.4); display: flex; align-items: center; justify-content: center;">
              <span style="font-size: 14px; color: var(--accent-neon-3);">📊</span>
            </div>
          ` : ''}
        </div>
        <div style="flex: 1; min-width: 0;">
          <div style="font-size: 14px; font-weight: 700; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; color: #fff;">
            ${escapeHtml(cleanTitle)} ${song.explicit ? '<span class="explicit-badge">E</span>' : ''}
          </div>
          <div style="font-size: 12px; color: var(--text-secondary); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; margin-top: 2px;">
            ${escapeHtml(song.artist)}
          </div>
        </div>
        <div class="queue-track-duration">
          ${formatTime(song.duration)}
        </div>
      </div>
    `;
  }).join('');

  container.querySelectorAll('.queue-track-row').forEach(row => {
    row.addEventListener('click', () => {
      const idx = parseInt(row.dataset.queueIndex, 10);
      hasUserPlayedAudio = true;
      if (playerEngine.queue.length === 0) {
        playerEngine.setQueue(allSongs, idx);
      } else {
        playerEngine.currentIndex = idx;
        playerEngine.loadCurrentTrack();
      }
      playerEngine.play();
    });
  });
}

/* ==========================================================================
   Wi-Fi P2P Transfer Integration
   ========================================================================== */
function initP2PTransferEvents() {
  const pinDisplay = document.getElementById('receiver-pin');
  const statusText = document.getElementById('p2p-status-text');
  const progressContainer = document.getElementById('p2p-progress-container');
  const progressFill = document.getElementById('p2p-progress-fill');
  const targetPinInput = document.getElementById('target-pin-input');
  const btnConnectPin = document.getElementById('btn-connect-pin');
  const dropZone = document.getElementById('p2p-send-dropzone');

  const initialPin = peerTransfer.startReceiverMode();
  pinDisplay.textContent = initialPin;

  peerTransfer.onPinGenerated = (pin) => {
    pinDisplay.textContent = pin;
  };

  peerTransfer.onPeerConnected = () => {
    statusText.textContent = "🟢 Connected! File transfer in progress...";
    dropZone.style.display = "block";
  };

  peerTransfer.onTransferProgress = (percent, filename) => {
    progressContainer.style.display = "block";
    progressFill.style.width = `${percent}%`;
    statusText.textContent = `Transferring "${filename}": ${percent}%`;
    if (percent >= 100) {
      setTimeout(() => {
        progressContainer.style.display = "none";
        statusText.textContent = "Transfer complete!";
      }, 1500);
    }
  };

  peerTransfer.onFileReceived = async (fileObj) => {
    const songData = await extractMetadata(fileObj);
    await musicStorage.saveSong(songData);
    await loadLibrarySongs();
    alert(`Received "${songData.title}" via Wi-Fi P2P and saved to offline library!`);
  };

  peerTransfer.onError = (msg) => {
    statusText.textContent = `⚠️ ${msg}`;
  };

  btnConnectPin.addEventListener('click', () => {
    const pin = targetPinInput.value.trim();
    if (pin.length !== 6) {
      alert("Please enter a valid 6-digit PIN!");
      return;
    }
    statusText.textContent = `Connecting to PIN ${pin}...`;
    peerTransfer.connectToReceiver(pin);
  });

  dropZone.addEventListener('click', () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = 'audio/*';
    input.onchange = (e) => {
      const file = e.target.files[0];
      if (file) peerTransfer.sendFile(file);
    };
    input.click();
  });
}

/* ==========================================================================
   Equalizer & Settings
   ========================================================================== */
function initEqualizerEvents() {
  const eqSliders = document.querySelectorAll('.eq-slider');
  const presetChips = document.querySelectorAll('[data-preset]');

  eqSliders.forEach((slider) => {
    slider.addEventListener('input', (e) => {
      const bandIndex = parseInt(e.target.dataset.band, 10);
      const val = parseFloat(e.target.value);
      document.querySelectorAll(`#eq-val-${bandIndex}`).forEach(el => {
        el.textContent = `${val > 0 ? '+' : ''}${val} dB`;
      });
      playerEngine.setEQBandGain(bandIndex, val);
    });
  });

  presetChips.forEach((chip) => {
    chip.addEventListener('click', () => {
      presetChips.forEach((c) => c.classList.remove('active'));
      chip.classList.add('active');

      const preset = chip.dataset.preset;
      const gains = playerEngine.applyEQPreset(preset);
      gains.forEach((gain, idx) => {
        document.querySelectorAll(`.eq-slider[data-band="${idx}"]`).forEach(s => s.value = gain);
        document.querySelectorAll(`#eq-val-${idx}`).forEach(el => {
          el.textContent = `${gain > 0 ? '+' : ''}${gain} dB`;
        });
      });
    });
  });
}

/* ==========================================================================
   Helpers
   ========================================================================== */
function formatTime(seconds) {
  if (isNaN(seconds) || seconds < 0) return '0:00';
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs < 10 ? '0' : ''}${secs}`;
}

function escapeHtml(str) {
  return (str || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
